/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/compoonents/AbsoluteSheet': RouteRecordInfo<'/compoonents/AbsoluteSheet', '/compoonents/AbsoluteSheet', Record<never, never>, Record<never, never>>,
    '/compoonents/AttrSheet': RouteRecordInfo<'/compoonents/AttrSheet', '/compoonents/AttrSheet', Record<never, never>, Record<never, never>>,
    '/compoonents/ContextMenu': RouteRecordInfo<'/compoonents/ContextMenu', '/compoonents/ContextMenu', Record<never, never>, Record<never, never>>,
    '/compoonents/CustomForm': RouteRecordInfo<'/compoonents/CustomForm', '/compoonents/CustomForm', Record<never, never>, Record<never, never>>,
    '/compoonents/DragSheet': RouteRecordInfo<'/compoonents/DragSheet', '/compoonents/DragSheet', Record<never, never>, Record<never, never>>,
    '/compoonents/DropSheet': RouteRecordInfo<'/compoonents/DropSheet', '/compoonents/DropSheet', Record<never, never>, Record<never, never>>,
    '/compoonents/JsonEditor': RouteRecordInfo<'/compoonents/JsonEditor', '/compoonents/JsonEditor', Record<never, never>, Record<never, never>>,
    '/compoonents/ResumeSheet': RouteRecordInfo<'/compoonents/ResumeSheet', '/compoonents/ResumeSheet', Record<never, never>, Record<never, never>>,
    '/compoonents/Toolbar': RouteRecordInfo<'/compoonents/Toolbar', '/compoonents/Toolbar', Record<never, never>, Record<never, never>>,
    '/drop-components/absolute/Header': RouteRecordInfo<'/drop-components/absolute/Header', '/drop-components/absolute/Header', Record<never, never>, Record<never, never>>,
    '/drop-components/resume/Blank': RouteRecordInfo<'/drop-components/resume/Blank', '/drop-components/resume/Blank', Record<never, never>, Record<never, never>>,
    '/drop-components/resume/Header': RouteRecordInfo<'/drop-components/resume/Header', '/drop-components/resume/Header', Record<never, never>, Record<never, never>>,
    '/drop-components/resume/ModuleTitle': RouteRecordInfo<'/drop-components/resume/ModuleTitle', '/drop-components/resume/ModuleTitle', Record<never, never>, Record<never, never>>,
    '/drop-components/resume/ProjectExperience': RouteRecordInfo<'/drop-components/resume/ProjectExperience', '/drop-components/resume/ProjectExperience', Record<never, never>, Record<never, never>>,
    '/drop-components/resume/SortList': RouteRecordInfo<'/drop-components/resume/SortList', '/drop-components/resume/SortList', Record<never, never>, Record<never, never>>,
    '/drop-components/resume/WorkExperience': RouteRecordInfo<'/drop-components/resume/WorkExperience', '/drop-components/resume/WorkExperience', Record<never, never>, Record<never, never>>,
    '/preview/': RouteRecordInfo<'/preview/', '/preview', Record<never, never>, Record<never, never>>,
  }
}
